# Exploration des ressources Ecommerce oList

In [73]:
import pandas as pd

### Quelques utiles pour l'exploration de données avec pandas

In [74]:
def display_structure(df) :

    pd_series = df.dtypes
    df_structure = pd.DataFrame(pd_series, columns=['Data Type']).reset_index()
    df_structure.rename(columns={'index': 'Column Name'}, inplace=True)
    return df_structure


def missing_values(df):
    missing_values = df.isnull().sum()
    missing_values_df = pd.DataFrame(missing_values, columns=['Missing Values']).reset_index()
    missing_values_df.rename(columns={'index': 'Column Name'}, inplace=True)
    return missing_values_df

def duplicate_values(df):
    initial_count = len(df)
    duplicate_count = df.duplicated().sum()
    duplicate_percentage = (duplicate_count / initial_count) * 100
    return {
        'name': df.name if hasattr(df, 'name') else 'DataFrame',
        'Initial Count': initial_count,
        'Duplicate Count': int(duplicate_count),
        'Duplicate Percentage': f"{int(duplicate_percentage)}%"
    }

### Chargement de toutes les ressources

In [75]:
df_customer = pd.read_csv("../data/olist_customers_dataset.csv")
df_geolocation = pd.read_csv("../data/olist_geolocation_dataset.csv")
df_order_items = pd.read_csv("../data/olist_order_items_dataset.csv")
df_order_payments = pd.read_csv("../data/olist_order_payments_dataset.csv")
df_orders = pd.read_csv("../data/olist_orders_dataset.csv")
df_products = pd.read_csv("../data/olist_products_dataset.csv")
df_sellers = pd.read_csv("../data/olist_sellers_dataset.csv")
df_category_name_translation = pd.read_csv("../data/product_category_name_translation.csv")

In [76]:
display_structure(df_customer)

                Column Name Data Type
0               customer_id       str
1        customer_unique_id       str
2  customer_zip_code_prefix     int64
3             customer_city       str
4            customer_state       str

In [77]:
display_structure(df_orders)

                     Column Name Data Type
0                       order_id       str
1                    customer_id       str
2                   order_status       str
3       order_purchase_timestamp       str
4              order_approved_at       str
5   order_delivered_carrier_date       str
6  order_delivered_customer_date       str
7  order_estimated_delivery_date       str

In [78]:
display_structure(df_order_items)

           Column Name Data Type
0             order_id       str
1        order_item_id     int64
2           product_id       str
3            seller_id       str
4  shipping_limit_date       str
5                price   float64
6        freight_value   float64

In [79]:
display_structure(df_products)

                  Column Name Data Type
0                  product_id       str
1       product_category_name       str
2         product_name_lenght   float64
3  product_description_lenght   float64
4          product_photos_qty   float64
5            product_weight_g   float64
6           product_length_cm   float64
7           product_height_cm   float64
8            product_width_cm   float64

In [80]:
display_structure(df_order_payments)

            Column Name Data Type
0              order_id       str
1    payment_sequential     int64
2          payment_type       str
3  payment_installments     int64
4         payment_value   float64

In [81]:
display_structure(df_geolocation)

                   Column Name Data Type
0  geolocation_zip_code_prefix     int64
1              geolocation_lat   float64
2              geolocation_lng   float64
3             geolocation_city       str
4            geolocation_state       str

In [82]:
display_structure(df_sellers)

              Column Name Data Type
0               seller_id       str
1  seller_zip_code_prefix     int64
2             seller_city       str
3            seller_state       str

### Interpretation  :

Nous avons pour chacune des ressources csv les données qui le constitues , une description de la signification de chaque libelé , qui parait d'ailleur tres explicite a la lecture ! et une idée des liens entre differentes tables    
**Liens** :  

```bash 

          Customer -----relation------> Orders 

          Order -------- Order_items ----- Products 

          Order_item <------relation----- Sellers 

          Orders ------- Tables_associatif ---- payments
                                |
                                |
                            Order_payments
```

##  Exploration des Valeurs Manquantes

In [83]:
missing_values(df_customer)

                Column Name  Missing Values
0               customer_id               0
1        customer_unique_id               0
2  customer_zip_code_prefix               0
3             customer_city               0
4            customer_state               0

In [84]:
missing_values(df_orders)

                     Column Name  Missing Values
0                       order_id               0
1                    customer_id               0
2                   order_status               0
3       order_purchase_timestamp               0
4              order_approved_at             160
5   order_delivered_carrier_date            1783
6  order_delivered_customer_date            2965
7  order_estimated_delivery_date               0

In [85]:
missing_values(df_order_items)

           Column Name  Missing Values
0             order_id               0
1        order_item_id               0
2           product_id               0
3            seller_id               0
4  shipping_limit_date               0
5                price               0
6        freight_value               0

In [86]:
missing_values(df_order_payments)

            Column Name  Missing Values
0              order_id               0
1    payment_sequential               0
2          payment_type               0
3  payment_installments               0
4         payment_value               0

In [87]:
missing_values(df_products)

                  Column Name  Missing Values
0                  product_id               0
1       product_category_name             610
2         product_name_lenght             610
3  product_description_lenght             610
4          product_photos_qty             610
5            product_weight_g               2
6           product_length_cm               2
7           product_height_cm               2
8            product_width_cm               2

In [88]:
missing_values(df_sellers)

              Column Name  Missing Values
0               seller_id               0
1  seller_zip_code_prefix               0
2             seller_city               0
3            seller_state               0

In [89]:
missing_values(df_geolocation)

                   Column Name  Missing Values
0  geolocation_zip_code_prefix               0
1              geolocation_lat               0
2              geolocation_lng               0
3             geolocation_city               0
4            geolocation_state               0

### Interpretation : 
Les produits possedent 610 lignes donts les informations descriptibles sont absentes 
(product_category_name,product_name_lenght,product_description_lenght). Ces produits restes neamoins identifié grace a leur product_id.

### Consequences : 
Bonne nouvelle on pourra utilisé ces données pour faire l'analyse des ventes 
La mauvaise nouvelle est que certain analyse par categorie  ne seront pas possible de realiser

De meme que pour le fichier Orders, nous des valeurs manquantes surs les caracteristiques (order_approved_at, order_delivered_carrier_date,	order_delivered_customer_date) respectivement (160.1783,2965)
La consequence directe, sont  les analyses qui impliqueraient ces differentes variables; elle seront difficilement realisables

## Exploration des Doubons

In [90]:
print('Customer', duplicate_values(df_customer))
print('Orders', duplicate_values(df_orders))
print('Order Items', duplicate_values(df_order_items))
print('Order Payments', duplicate_values(df_order_payments))
print('Products', duplicate_values(df_products))
print('Sellers', duplicate_values(df_sellers))
print('Geolocation', duplicate_values(df_geolocation))

Customer {'name': 'DataFrame', 'Initial Count': 99441, 'Duplicate Count': 0, 'Duplicate Percentage': '0%'}
Orders {'name': 'DataFrame', 'Initial Count': 99441, 'Duplicate Count': 0, 'Duplicate Percentage': '0%'}
Order Items {'name': 'DataFrame', 'Initial Count': 112650, 'Duplicate Count': 0, 'Duplicate Percentage': '0%'}
Order Payments {'name': 'DataFrame', 'Initial Count': 103886, 'Duplicate Count': 0, 'Duplicate Percentage': '0%'}
Products {'name': 'DataFrame', 'Initial Count': 32951, 'Duplicate Count': 0, 'Duplicate Percentage': '0%'}
Sellers {'name': 'DataFrame', 'Initial Count': 3095, 'Duplicate Count': 0, 'Duplicate Percentage': '0%'}
Geolocation {'name': 'DataFrame', 'Initial Count': 1000163, 'Duplicate Count': 261831, 'Duplicate Percentage': '26%'}

### Observation : 
Le fichier Geolocation comportes 26% de valeur dupliquer soit 261831 lignes / 1000163 lignes. afin de savoir la decision adequate a prendre pour ces donnees dupliqués, nous allons pousser notre analyse et grouper ces lignes cote cote pour comment elles sont constitués, sont t'elle parfaitement identiques ou pas ?

In [91]:
df_geolocation[df_geolocation.duplicated(keep=False)].sort_values(by=list(df_geolocation.columns))

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
519,1001,-23.551337,-46.634027,sao paulo,SP
583,1001,-23.551337,-46.634027,sao paulo,SP
818,1001,-23.551337,-46.634027,sao paulo,SP
206,1001,-23.550498,-46.634338,sao paulo,SP
429,1001,-23.550498,-46.634338,sao paulo,SP
...,...,...,...,...,...
999899,99980,-28.387432,-51.847727,david canabarro,RS
999958,99980,-28.387059,-51.848964,david canabarro,RS
1000129,99980,-28.387059,-51.848964,david canabarro,RS
999775,99980,-28.386689,-51.847091,david canabarro,RS
1000133,99980,-28.386689,-51.847091,david canabarro,RS

## Interpretation : 
On constate qu'il ya des lignes parfaitement identiques . l'approche la plus simple de resolution du probleme serait de conserver une seule occurence des lignes dupliqués .
    
df.drop_duplicates(subset=['name_column'],inplace=True)